# Generated by Django 2.2.4 on 2019-10-31 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTypeModel',
            fields=[
                ('pt_no', models.IntegerField(primary_key=True, serialize=False)),
                ('pt_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('p_no', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=100)),
                ('p_price', models.FloatField()),
                ('p_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductTypeModel')),
            ],
        ),
    ]
